Repository thinkarlabs/P23-003-MalnutritionDashboard, pull requests merged in 2023-02, with the labels that each got.

#24 Feature/18 convert common admin menu as component
  .gitignore
  Backend/config/database.py
  Backend/model/model.py
  Backend/routes/routes.py
  Backend/schemas/schema.py
  FrontEnd/index.html
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.vue
  FrontEnd/src/router/index.ts
  FrontEnd/src/stores/ngo.ts
  FrontEnd/src/views/AddNgoView.vue
  FrontEnd/src/views/DashboardView.vue
  FrontEnd/src/views/HomeView.vue
  FrontEnd/src/views/NgosView.vue
  FrontEnd/src/views/PageNotFoundView.vue
  main.py
Labels: Admin Module

#39 crud operations for donors in ngo login
  Backend/config/database.py
  Backend/model/model.py
  Backend/routes/routes.py
  Backend/schemas/schema.py
  main.py
Labels: Ngo Module

#40 Feature/34 PWA baseline feature
  .gitignore
  .vscode/settings.json
  Backend/model/model.py
  Backend/routes/routes.py
  Backend/schemas/schema.py
  FrontEnd/.gitignore
  FrontEnd/index.html
  FrontEnd/package-lock.json
  FrontEnd/package.json
  FrontEnd/src/App.vue
  FrontEnd/src/components/HelloWorld.vue
  FrontEnd/src/components/TheWelcome.vue
  FrontEnd/src/main.js
  FrontEnd/src/registerServiceWorker.js
  FrontEnd/src/router/index.js
  FrontEnd/src/stores/counter.ts
  FrontEnd/src/stores/ngo.js
  FrontEnd/src/views/AboutView.vue
  FrontEnd/src/views/AddNgoView.vue
  FrontEnd/src/views/HomeView.vue
  FrontEnd/vite.config.js
  main.py
  requirements.txt
Labels: Repo_setup
